cronos:
  yugabyte:
    keyspace: cronos
    hostname: ${DB_HOSTNAME:127.0.0.1}
    port: 9042

spring:
  profiles:
    active: local
  application:
    name: checkout-microservice
server:
  port: 8086

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    hostname: ${spring.application.name}