spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: ""
  messages:
    basename: validation
  mvc:
    view:
      prefix: /
      suffix: .jsp

yugastore:
  redirect:
    url: https://yugastore-ui.cfapps.io

server:
  port: 8085

logging:
  level:
    root: info
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    org.hibernate.type.descriptor.BasicBinder: trace

