##################################################################################################
# API Gateway microservice
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: gcr.io/dataengineeringdemos/yugabyte/api-gateway:v0.1
        envFrom:
        - configMapRef:
            name: environment-config
        ports:
        - containerPort: 8081
