##################################################################################################
# checkout microservice
##################################################################################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: checkout-microservice-properties
data:
  spring.data.cassandra.keyspace-name: cronos
  spring.data.cassandra.contact-points: yb-tservers.yb-demo.svc.cluster.local
  spring.data.cassandra.port: "9042"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-microservice
spec:
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-microservice
  labels:
    app: checkout
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
      version: v1
  template:
    metadata:
      labels:
        app: checkout
        version: v1
    spec:
      containers:
      - name: checkout
        image: gcr.io/dataengineeringdemos/yugabyte/yugastore-checkout:v0.1
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: checkout-microservice-properties
        ports:
        - containerPort: 8086
