apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-eureka
  labels:
    app: eureka
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
      version: v1
  template:
    metadata:
      labels:
        app: eureka
        version: v1
    spec:
      containers:
      - name: eureka
        image: gcr.io/dataengineeringdemos/yugabyte/eureka-server-local:v0.1
        envFrom:
        - configMapRef:
            name: environment-config
        ports:
        - containerPort: 8761
