##################################################################################################
# products microservice
##################################################################################################
kind: ConfigMap
apiVersion: v1
metadata:
  name: products-microservice-properties
data:
  spring.data.cassandra.keyspace-name: cronos
  spring.data.cassandra.contact-points: yb-tservers.yb-demo.svc.cluster.local
  spring.data.cassandra.port: "9042"
---
apiVersion: v1
kind: Service
metadata:
  name: products-microservice
spec:
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice
  labels:
    app: products
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      version: v1
  template:
    metadata:
      labels:
        app: products
        version: v1
    spec:
      containers:
      - name: products
        image: gcr.io/dataengineeringdemos/yugabyte/yugastore-products:v0.1
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: products-microservice-properties
        ports:
        - containerPort: 8082
