kind: ConfigMap
apiVersion: v1
metadata:
  name: search-microservice-v1-properties
data:
  REDIS_HOSTNAME: redis
  REDIS_PORT: "6380"
---
apiVersion: v1
kind: Service
metadata:
  name: search-microservice
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-microservice-v1
  labels:
    app: search
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      version: v1
  template:
    metadata:
      labels:
        app: search
        version: v1
    spec:
      containers:
      - name: search
        image: gcr.io/dataengineeringdemos/yugabyte/yugastore-search:v0.1
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: search-microservice-v1-properties
        ports:
        - containerPort: 8888
