spring:
  profiles:
    active: local
  application:
    name: products-microservice
    jpa:
      database: yugabyte
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
    data:
      jpa:
        repositories:
          enabled: true
  datasource:
    hikari:
      username: yugabyte
      password: yugabyte
      maximumPoolSize: 10
      data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
      data-source-properties:
        serverName: ${DB_HOSTNAME:127.0.0.1}
        portNumber: 5433
        databaseName: yugabyte
        additionalEndpoints:
        topologyKeys:

server:
  port: 8082
  storenum: 99

logging:
  level:
    root: info
    org.springframework.wen: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.BasicBinder: trace

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}
  instance:
    hostname: ${spring.application.name}
